/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package CPresentacion;


import datoscarga.DatosCarga;
import java.io.File;
// import java.io.FileWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author TNFUSER-07
 */
public class PanelPresentacion extends javax.swing.JFrame {
    //String pathEntrada = "C:\\Users\\tnfuser11\\My Cloud\\MHP ownCloud\\05 PROYECTOS NetBeans\\Migración PW\\prueba2.xlsx";
    //String pathSalida = "C:\\Users\\tnfuser11\\Desktop\\Compartido MV\\prueba2.xml";
    
    // MIG_JUS
    String pathEntrada = "C:\\Users\\tnfuser11\\My Cloud\\MHP ownCloud\\05 PROYECTOS NetBeans\\Migración PW\\MIG_JUS_v1.xlsx";
    String pathSalida = "C:\\Users\\tnfuser11\\Desktop\\Compartido MV\\MIG_JUS_v1.xml";
    
    /**
     * Creates new form PanelPresentacion
     */
    public PanelPresentacion() {
        //initComponents();
        migrarDatos();
        System.exit(0);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        abrirArchivo = new javax.swing.JButton();
        guardarArchivo = new javax.swing.JButton();
        txtPathEntrada = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombre.setText("Migración PrevenWeb");

        abrirArchivo.setText("Abrir");
        abrirArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirArchivoActionPerformed(evt);
            }
        });

        guardarArchivo.setText("Guardar");
        guardarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarArchivoActionPerformed(evt);
            }
        });

        txtPathEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPathEntradaActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(guardarArchivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSalir))
                            .addComponent(txtPathEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abrirArchivo))
                    .addComponent(lblNombre))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblNombre)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPathEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abrirArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarArchivo)
                    .addComponent(btnSalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirArchivoActionPerformed
        // Abrir cuadro de dialogo para elegir fichero de entrada
        try {
           JFileChooser file = new JFileChooser();
           file.setCurrentDirectory(new File("."));           
           FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos XLSX", "xlsx");
           file.setFileFilter(filtro);
           file.showOpenDialog(this); 
           /**abrimos el archivo seleccionado*/
           File ficheroEntrada = file.getSelectedFile();
           pathEntrada = ficheroEntrada.getAbsolutePath();
        }
        catch (Exception ex) {
             JOptionPane.showMessageDialog(null,ex+"" + "\nNo se ha encontrado el archivo", "ADVERTENCIA!!!",JOptionPane.WARNING_MESSAGE);
        }
        
        txtPathEntrada.setText(pathEntrada);
    }//GEN-LAST:event_abrirArchivoActionPerformed

    private void guardarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarArchivoActionPerformed
        // guardarArchivo();
        if (pathEntrada == null) {
               JOptionPane.showMessageDialog(null, "Seleccione primero un fichero de entrada", "Información",JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
               // Abrir cuadro de dialogo para solicitar el XML de destino 
               JFileChooser file = new JFileChooser();
               file.setCurrentDirectory(new File("."));
               FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos XML", "xml");
               file.setFileFilter(filtro);
               file.showSaveDialog(this);
               File guarda = file.getSelectedFile();
               pathSalida = guarda.getAbsolutePath();

               //guardamos el archivo y le damos el formato directamente
               if (pathSalida == null) {
                 JOptionPane.showMessageDialog(null, "Seleccione fichero de salida", "Información",JOptionPane.INFORMATION_MESSAGE);
               } else {
                    migrarDatos();
               }

           } catch (Exception ex) {
              JOptionPane.showMessageDialog(null, "Su archivo no se ha guardado", "Advertencia",JOptionPane.WARNING_MESSAGE);
           }
        }
    }//GEN-LAST:event_guardarArchivoActionPerformed

    private void migrarDatos() {
        // Cargar datos
        DatosCarga datos = new DatosCarga(pathEntrada);
        // Escribo los datos en el fichero destino
        datos.guardaFicheroXML(pathSalida);
        // Si todo ha ido bien mostrar mensaje de éxito
        JOptionPane.showMessageDialog(null, "El archivo se ha guardado Exitosamente", "Información",JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void txtPathEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPathEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPathEntradaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirArchivo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton guardarArchivo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField txtPathEntrada;
    // End of variables declaration//GEN-END:variables
}
